### ISSUE TITLE
"Socket closed by remote peer" - GCDAsyncSocket Error Code 7

### ISSUE THREAD

**Issue by indragiek** [robbiehanson/XMPPFramework#131]
After a period of inactivity, the stream disconnects with the following error:

```
Error Domain=GCDAsyncSocketErrorDomain Code=7 "Socket closed by remote peer" UserInfo=0x7ff222d0ce90 {NSLocalizedDescription=Socket closed by remote peer}, {
    NSLocalizedDescription = "Socket closed by remote peer";
}
```

The `XMPPReconnect` module reconnects to the server, but it goes into an infinite loop of periodically disconnecting (with the above error) and reconnecting, and even after reconnecting it doesn't receive any more data from the server until the stream is explicitly disconnected and connected again. I found some old discussion on this issue but wasn't sure if it was still relevant:

https://groups.google.com/forum/#!msg/xmppframework/6RZY3fN73_w/nv8fEGgJiQUJ

Thanks.

**Comment by Bhat123** [comment]
Hi im facing the same problem can any one help to fix. this issue

**Comment by gleeeli** [comment]
How to solve this problem???

**Comment by gleeeli** [comment]
i fixed it by reduce the heart time(7 minute)

**Comment by vickyrappier** [comment]
Hello Gleeeli, can you please guide how you fixed this problem, I have tried the ping but still the same issue although the ping pong happening.

This also hence making me loose some message while the reconnect is happening and missed stanza. since the server guy is informing that I am connecting to expired session not the resume way that is to be worked.

**Comment by gleeeli** [comment]
我是将心跳时间从十分钟减到五分钟解决的（reduce the heart time from ten minutes to five minutes）
----- 原始邮件 -----
发件人："Vicky Dhas (Rappier Pte Ltd)" <notifications@github.com>
收件人：robbiehanson/XMPPFramework <XMPPFramework@noreply.github.com>
抄送人：gleeeli <gleeeli@sina.com>
主题：Re: [XMPPFramework] "Socket closed by remote peer" - GCDAsyncSocket Error Code 7 (#131)
日期：2016年01月06日 15点23分

Hello Gleeeli, can you please guide how you fixed this problem, I have tried the ping but still the same issue although the ping pong happening.

This also hence making me loose some message while the reconnect is happening and missed stanza. since the server guy is informing that I am connecting to expired session not the resume way that is to be worked.

&mdash;

**Comment by yql15627285171** [comment]
Please  tell me details to fit it,thanks

**Comment by posswordkey** [comment]
I want konw  anyone solve this problem?? I have this problem now

**Comment by githupchenqiang** [comment]
how to deal it  I want to know

**Comment by gleeeli** [comment]
sorry, i‘m not user xmpp when get this mistake。i get this mistake when i use GCDAsyncsocket。i solve this problem by reduce the heart time in five minute。
----- 原始邮件 -----
发件人：QiangChen <notifications@github.com>
收件人：robbiehanson/XMPPFramework <XMPPFramework@noreply.github.com>
抄送人：gleeeli <gleeeli@sina.com>,  Comment <comment@noreply.github.com>
主题：Re: [robbiehanson/XMPPFramework] "Socket closed by remote peer" - GCDAsyncSocket Error Code 7 (#131)
日期：2016年06月17日 18点53分

how to deal it  I want to know

&mdash;

**Comment by gleeeli** [comment]
你可以加我QQ 295981743
----- 原始邮件 -----
发件人：QiangChen <notifications@github.com>
收件人：robbiehanson/XMPPFramework <XMPPFramework@noreply.github.com>
抄送人：gleeeli <gleeeli@sina.com>,  Comment <comment@noreply.github.com>
主题：Re: [robbiehanson/XMPPFramework] "Socket closed by remote peer" - GCDAsyncSocket Error Code 7 (#131)
日期：2016年06月17日 18点53分

how to deal it  I want to know

&mdash;

**Comment by ranjin** [comment]
11

**Comment by nawar** [comment]
this is how to enable it 

```swift
let autoPing = XMPPAutoPing()
autoPing.activate(xmppStream)
```

**Comment by pmehul55** [comment]
Hello Everyone,

 - MongooseIM 2.0.0
 
Getting this error in some random time after connected to server and also notice one thing is that it always come when network connection is "Mobile Data"
  
**Domain=GCDAsyncSocketErrorDomain Code=7 "Socket closed by remote peer" UserInfo={NSLocalizedDescription=Socket closed by remote peer}**

Please help.

**Comment by jelordreygulle** [comment]
mqttDidDisconnect: Socket closed by remote peer ? what could be the problem?

**Comment by skumarm** [comment]
I am also getting the same error. How to get rid of this. 
I am using 5281 as the port number for SSL. 
Please help...

**Comment by nawar** [comment]
There might be several problems related to that like changing connection speeds, switching from WiFi to wireless data. So use a combination of XEP-0199 and XEP-0184

**Comment by vadlani9** [comment]
In my case we are using 2 types of mqtt connections.
1) mqtt://ourhostname:1884 [Like http://.....] Non secured connections
2) mqtts://ourhostname:1885 [Like https://....] Securied connections

I got the same error when i try to use 1885 port numer.

I have added below code in my existing code:
```
mqttReference?.dispatchQueue = DispatchQueue.global(qos: .userInitiated)
        //mqttReference?.logLevel = .debug
        mqttReference?.enableSSL = true
        mqttReference?.sslSettings = [
            GCDAsyncSocketManuallyEvaluateTrust: NSNumber(booleanLiteral: true),
            GCDAsyncSocketUseCFStreamForTLS: NSNumber(booleanLiteral: false),
            kCFStreamSSLPeerName as String: "" as NSString,
            GCDAsyncSocketSSLProtocolVersionMin: NSNumber(integerLiteral: Int(SSLProtocol.tlsProtocol1.rawValue)),
            GCDAsyncSocketSSLProtocolVersionMax: NSNumber(integerLiteral: Int(SSLProtocol.tlsProtocol12.rawValue)),
        ]
```
        
My complete code now:

/```
/  let clientID = "CocoaMQTT-" + String(ProcessInfo().processIdentifier)
        mqttReference = CocoaMQTT(clientID: "", host: mqttProfile.baseURL, port: UInt16(mqttProfile.port))
        mqttReference?.username = mqttProfile.userName
        mqttReference?.password = mqttProfile.password
        mqttReference?.allowUntrustCACertificate = true
        
        
        mqttReference?.dispatchQueue = DispatchQueue.global(qos: .userInitiated)
        //mqttReference?.logLevel = .debug
        mqttReference?.enableSSL = true
        mqttReference?.sslSettings = [
            GCDAsyncSocketManuallyEvaluateTrust: NSNumber(booleanLiteral: true),
            GCDAsyncSocketUseCFStreamForTLS: NSNumber(booleanLiteral: false),
            kCFStreamSSLPeerName as String: "" as NSString,
            GCDAsyncSocketSSLProtocolVersionMin: NSNumber(integerLiteral: Int(SSLProtocol.tlsProtocol1.rawValue)),
            GCDAsyncSocketSSLProtocolVersionMax: NSNumber(integerLiteral: Int(SSLProtocol.tlsProtocol12.rawValue)),
        ]
        
        
        mqttReference?.autoReconnect = true
        mqttReference?.backgroundOnSocket = mqttProfile.allowBackgroundMQTT
        mqttReference?.delegate = self
        do {
            if((mqttReference?.connect())!){
               ...........

```

Now it's working fine.
