### ISSUE TITLE
XMPP socket fails to connect when connected to a IPv6 only network

### ISSUE THREAD

**Issue by polmum** [robbiehanson/XMPPFramework#718]
Apple recently announced that Starting June 1, 2016 all apps submitted to the App Store must support IPv6-only networking.
I set up a network following Apple's documentation instructions in [https://developer.apple.com/library/mac/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW16], and when trying to use the library the GCDAsyncSocket socket fails to connect.
After investigating a bit the issue seems to be that the XMPP server is returning both IPv4 and IPv6 addresses, but the socket is only trying to connect with the preferred one, which is IPv4. When it fails to connect, it does not retry with the IPv6 address.

I'm not really sure if this is an issue that should be fixed in the GCDAsyncSocket library or here in the XMPP one.
A possible solution would be to set IPv6 as the preferred address, but right now that is not possible as the XMPPStream class is not exposing the socket as a property, nor does it provide a method to set this configuration.

Any help and guidance is really appreciated

**Comment by hei9gag** [comment]
+1

**Comment by chrisballinger** [comment]
See https://github.com/robbiehanson/CocoaAsyncSocket/issues/315

**Comment by hei9gag** [comment]
Thanks. So we need to wait CocoaAsyncSocket to implement Happy Eyeballs algorithm.

**Comment by polmum** [comment]
Yes, it would appear that the CocoaAsyncSocket library should be the one to be updated.
Should I close this issue, or leave it opened until CocoaAsyncSocket is updated?

**Comment by brianhei** [comment]
I think just leave it open and see any changes require to make after the CocoaAsyncSocket is updated.

**Comment by tianglin** [comment]
Agree with @brianhei , just leave it open, and hopes the CocoaAsyncSocket will update as soon as possible.

**Comment by xuxue1988** [comment]
http://blog.csdn.net/xuxue1072/article/details/51481102,this solve the problem

**Comment by soulfly** [comment]
Yeah, 
agree with @xuxue1988 , works on our side as well

**Comment by Asura19** [comment]
Thanks so much , @xuxue1988， I got this problem solved with this method

**Comment by akhiljohny** [comment]
@xuxue1988  i still cant login in ipV6. Apple is rejecting my xmpp chat app.

**Comment by akhiljohny** [comment]
@Asura19 can u login xmpp chat in IPV6 network..??
Apple accepted your application..??
plz tell me how to do it..??

**Comment by soulfly** [comment]
Hi guys, 

had the same issue,

this is our fix that works and Apple approves all apps without problems

`asyncSocket.IPv4PreferredOverIPv6 = NO;`

do it in Core/XMPPStream.m inside 'init' method, when you initialize a socket:

```
// Initialize socket
asyncSocket = [[GCDAsyncSocket alloc] initWithDelegate:self delegateQueue:xmppQueue];
asyncSocket.IPv4PreferredOverIPv6 = NO;
```

**Comment by akhiljohny** [comment]
@soulfly thank you... i add this code n am going to submit to appstore....

**Comment by soulfly** [comment]
@akhiljohny yeah, we submitted already 5-10 apps and it works

**Comment by soulfly** [comment]
Anyway you can test it on your end before submission

Please follow this guide
https://developer.apple.com/library/mac/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW16

just setup IPv6 WiFi network on your MacMini and connect with your iPhone.
If it works well then you can submit your app.

**Comment by akhiljohny** [comment]
@soulfly i tried it... but there is no option for CreateNAT64 network in my iMac ...

**Comment by Asura19** [comment]
@akhiljohny I can login xmpp chat in IPV6 network with this method. You can test with your mac:
1. Connect your mac to Internet with thunderbolt
2. Click sharing network button with "option" key pressed(my English is so bad, I don't know whether you can understand.....), if you don't press option key, it will not show "CreateNAT64", if your mac or OS X version is old, also it won't show  "CreateNAT64".
3. that is @soulfly told you.
 Good luck to you!

**Comment by akhiljohny** [comment]
@Asura19 ok thank you. i'll do it

**Comment by chrisballinger** [comment]
I'm not sure if simply setting `IPv4PreferredOverIPv6 = NO` is enough, but this is a good enough hotfix for now. If a DNS server returns invalid IPv6 addresses alongside valid IPv4 records it will fail because it won't fallback to IPv4, but I guess that's not really our fault. 

Can everyone confirm that setting `IPv4PreferredOverIPv6 = NO` doesn't break anything on previous iOS versions? If there are no objections I'll merge this change into the master branch.

**Comment by akhiljohny** [comment]
@soulfly @Asura19 @chrisballinger My application rejected again... still cant login in IPV6 only network...

**Comment by Asura19** [comment]
@akhiljohny Have you tested IPV6 yourself ?

**Comment by akhiljohny** [comment]
@Asura19  i cant test it... because am in India... no chance for IPV6 network... and my mac doesn't have the option to create NAT64... i tried a lot... plz advice

**Comment by Asura19** [comment]
@akhiljohny 
1. I think there is ipv6 in India
2. Is.your iMac too old ? Borrow a mac if your can.Or use ifconfig to check whether your mac support ipv6
3. Ask your xmpp server developer whether your server support ipv6

**Comment by akhiljohny** [comment]
@Asura19 yes we have IPV6 network but also supports IPV4, in this network my application works fine... but IPV6 only network it fails... My iMac is new i tried many options to activate NAT64 network but doesn't display the option "Create NAT64 network"...
is there any server side update need to support IPV6 only network...  ???

**Comment by Asura19** [comment]
@akhiljohny when you click sharing network you should press "option/alt" key, at the same time.

**Comment by akhiljohny** [comment]
@Asura19 thank you... i created NAT64 network....

**Comment by akhiljohny** [comment]
@Asura19 but my main problem is its still not connecting when in IPV6 network...

**Comment by Asura19** [comment]
@akhiljohny   xuxue1988's method doesn't work?

**Comment by akhiljohny** [comment]
@Asura19 i tried his method... it doesn't work...

**Comment by hei9gag** [comment]
@akhiljohny Try set a break point in GCDAsyncSocket line 2186 - (BOOL)connectWithAddress4:(NSData *)address4 address6:(NSData *)address6 error:(NSError **)errPtr

and check whether it is try to use IPv6 to connect in NAT64 network

**Comment by akhiljohny** [comment]
@hei9gag ok i'll check it

**Comment by hei9gag** [comment]
@akhiljohny For my side, I have changed the library a bit. If GCDAsyncSocket lookupHost returns ipv6 address, I will set [asyncSocket setIPv4PreferredOverIPv6:NO]. It works in NAT64 network and approved by Apple

**Comment by akhiljohny** [comment]
@hei9gag @Asura19 @soulfly My App now can login in NAT64 network... i checked it again and again...
i submitted to AppStore for approval ...

**Comment by hei9gag** [comment]
@akhiljohny Welcome and hope for the best :)

**Comment by akhiljohny** [comment]
@hei9gag @chrisballinger @Asura19 @soulfly Thank you all of you.... finally my app accepted by AppStore....

**Comment by chathudan** [comment]
thank you guys

**Comment by alberttai1** [comment]
I'm having this problem right now -- been rejected 6 times so the struggle is very real. 

I tried the @soulfly method and also the commit from @chrisballinger but it didn't work. Would it possible to be my server issue for DNS? My server does not have a AAAA record since it does not have a ipv6 address (hosted on Azure). I'm trying to get my app approved as quick as possible due to a pilot but this has been a huge struggle.

**Comment by akhiljohny** [comment]
@alberttai1 Follow this 
https://github.com/SametDEDE/CocoaAsyncSocket/commit/ed8bfaf30f96bbfc59d79e9f7ea78d16702f964e#commitcomment-17832416

**Comment by akhiljohny** [comment]
@alberttai1 
do it in Core/XMPPStream.m inside '-(id)init' method, when you initialize a socket:

// Initialize socket
asyncSocket = [[GCDAsyncSocket alloc] initWithDelegate:self delegateQueue:xmppQueue];
asyncSocket.IPv4PreferredOverIPv6 = NO;

**Comment by now1130** [comment]
@akhiljohny @soulfly ,your openfire's hostName is ipv4 or ipv6?

**Comment by soulfly** [comment]
@now1130  ipv4

**Comment by now1130** [comment]
@soulfly thanks, my hostName is ipv4(xxx.xxx.xxx.xxx),but xmpp show log :"Error Domain=NSPOSIXErrorDomain Code=51 "Network is unreachable" ", Even if I set GCDAsyncSocket like akhiljohny.Is it because my server is AWS?

**Comment by akhiljohny** [comment]
@now1130  i dont know why this happening... but please follow this too... You need to change some code in GCDAsyncSocket.m 
[https://github.com/SametDEDE/CocoaAsyncSocket/commit/ed8bfaf30f96bbfc59d79e9f7ea78d16702f964e](url)

**Comment by akhiljohny** [comment]
@now1130 https://github.com/SametDEDE/CocoaAsyncSocket/commit/ed8bfaf30f96bbfc59d79e9f7ea78d16702f964e

**Comment by now1130** [comment]
@akhiljohny thanks,I'd change in GCDAsyncSocket.m. my hostName is ipv4, but the hostName does not auto change to ipv6 in ipv6's network.

**Comment by purepure** [comment]
Hi guy!
I applied this fix to my app: 
asyncSocket = [[GCDAsyncSocket alloc] initWithDelegate:self delegateQueue:xmppQueue];
asyncSocket.IPv4PreferredOverIPv6 = NO;

But after that I got this issue when trying to login:
Error Domain=NSPOSIXErrorDomain Code=65 "No route to host" UserInfo={NSLocalizedDescription=No route to host, NSLocalizedFailureReason=Error in connect() function}

It happened on ipad 9.3 that running ipv6

Anyguy get this same ?

**Comment by rashoodkhan** [comment]
Hey. Anyone has deployed an XMPP Server on Azure? How did you get around with the ipV6 issue as azure as of today is not providing ipv6 support to machines? I have made the changes as described above in XMPPSteam.m and GCDAsycnSocket. 

I'm getting the error when connecting to the XMPP Azure Machine with error code 51. Any help regarding this will be appreciated?

**Comment by hei9gag** [comment]
@purepure I think you first need to check whether the host can returns ipv6 address and set IPv4PreferredOverIPv6 to No

**Comment by purepure** [comment]
yes, I enable both ipv4 & ipv6 on my server. I verify by using this site: http://ipv6-test.com/validate.php. The result is ipv6, ipv4 was enabled. So there is no need to worry about server side. 
If I comment this line: asyncSocket.IPv4PreferredOverIPv6 = NO; it work on ipv4 at least, but when I use that code, I return error on ipv4.

Any suggestion?

**Comment by hei9gag** [comment]
maybe you can set a break point and check the logic - (BOOL)connectWithAddress4:(NSData )address4 address6:(NSData *)address6 error:(NSError *)errPtr

For our project, we don't have any problems using iPad (9.3) to connect either IPv4 or IPv6 network.

**Comment by purepure** [comment]
Some guys tell me modify code like this:
https://github.com/SametDEDE/CocoaAsyncSocket/commit/ed8bfaf30f96bbfc59d79e9f7ea78d16702f964e

I am not sure it relate to this issue or not.

**Comment by purepure** [comment]
@akhiljohny I applied your code but it still error:
Error Domain=NSPOSIXErrorDomain Code=65 "No route to host" UserInfo={NSLocalizedDescription=No route to host, NSLocalizedFailureReason=Error in connect() function}

Can you guide me at that point ?

**Comment by purepure** [comment]
Hi guy!
Sorry about that mess, adding this line asyncSocket.IPv4PreferredOverIPv6 = NO actually works. I forgot to update xmpp framework so it make that line failed in my project. 
I am not sure this is same reason as someone else but just noted here. 
1. Keep update xmpp framework
2. adding that line to xmppstream.m

Hope that help
p/s: also thank to @akhiljohny, he made me look back to my own project

cheer!

**Comment by akhiljohny** [comment]
@purepure 👍

**Comment by bikash-bdm** [comment]
if I set [asyncSocket setPreferIPv4OverIPv6:NO], the socket is not connecting in IP4 network. Can anyone help me in this?

**Comment by purepure** [comment]
Your server must support both ipv4 + ipv6.

**Comment by prakash-brainium** [comment]
**[asyncSocket setPreferIPv4OverIPv6:NO]** always try to make the connection using IPv6 even if I'm in IPv4 network, that's why the socket connection fails in IPv4 but works in IPv6. But if I comment out the line in IPv4, it works fine but doesn't work in IPv6 network. Can you help me guys to set up the connection for both network?

**Comment by prakash-brainium** [comment]
Ok guys. I modified the socket a little and now it's working fine.

**Comment by akhiljohny** [comment]
hey guys, I want to retrieve my Profile name from xmpp. I tried my methods but failed. Please help me.

**Comment by prakash-brainium** [comment]
**[_xmppvCardTempModule fetchvCardTempForJID:[XMPPJID jidWithString:jid] ignoreStorage:YES];**  here jid will be your target jid for which you want to retrieve the name. Then in **-(void)xmppvCardTempModule:(XMPPvCardTempModule *)vCardTempModule didReceivevCardTemp:(XMPPvCardTemp *)vCardTemp forJID:(XMPPJID *)jid** you will get the name by 
XMPPvCardTemp *vCard = [[XMPPvCardCoreDataStorage sharedInstance] vCardTempForJID:jid xmppStream:self.xmppStream];
NSString *Name = vCard.nickname;
Don't forgot the set the delegate true

**Comment by akhiljohny** [comment]
@prakash-brainium ok thanku. let me try this

**Comment by ankits16** [comment]
@prakash-brainium can you please share the changes made to the socket cause I have used asyncSocket.IPv4PreferredOverIPv6 = NO; and it was working fine intially but now all of a sudden its not connecting on 3G networks(Airtel, Vodafone etc) but works fine on LTE(Jio)

**Comment by prakash-brainium** [comment]
When **asyncSocket.IPv4PreferredOverIPv6 = NO;** is set, what I have done is, first I'm trying the connection with IPv6 and if connection fails retrying with IPv4. This way it'll work for both IPv6 and IPv4 network. Follow the steps to get the changes:-
1. In GCDAsyncSocket.m, go to method - (BOOL)connectWithAddress4:(NSData *)address4 address6:(NSData *)address6 error:(NSError **)errPtr and add the following code after the line 
**int result = connect(socketFD, (const struct sockaddr *)[address bytes], (socklen_t)[address length]);**

if (result != 0) {
            
            socket6FD = SOCKET_NULL;
            socket4FD = socket(AF_INET, SOCK_STREAM, 0);
            
            socketFD = socket4FD;
            address = address4;
            connectInterface = connectInterface4;
            
            result = connect(socketFD, (const struct sockaddr *)[address bytes], (socklen_t)[address length]);
        }

**Comment by ankits16** [comment]
@prakash-brainium cool worked fine for me

**Comment by miighty** [comment]
@rashoodkhan What solution did you come to?

**Comment by bhooshanpatil** [comment]
try in GCDAsyncSocket.m
`- (void)setIPv6Enabled:(BOOL)flag
{
	// Note: YES means kIPv6Disabled is OFF
	
	dispatch_block_t block = ^{
		
        if (flag)
            config &= ~kIPv6Disabled;
        else
            config |= kIPv6Disabled;
	};
	
	if (dispatch_get_specific(IsOnSocketQueueOrTargetQueueKey))
		block();
	else
		dispatch_async(socketQueue, block);
}`

**Comment by Amitmundra** [comment]
XMPPFramwork does not connected on low network, what should we do to resolve low network issue to make connection stable?

**Comment by Hardiktspaceo** [comment]
@akhiljohny. i have a same isssue my client can not send receive message in mobile network over LTE. so can you please provide changes required to solve this issue.

**Comment by akhiljohny** [comment]
@Hardiktspaceo  replace lookupHost function in XMPPStream.m file with this

+ (NSMutableArray *)lookupHost:(NSString *)host port:(uint16_t)port error:(NSError **)errPtr
{
	LogTrace();
	
	NSMutableArray *addresses = nil;
	NSError *error = nil;
    
    
	
	if ([host isEqualToString:@"localhost"] || [host isEqualToString:@"loopback"])
	{
		// Use LOOPBACK address
		struct sockaddr_in nativeAddr4;
		nativeAddr4.sin_len         = sizeof(struct sockaddr_in);
		nativeAddr4.sin_family      = AF_INET;
		nativeAddr4.sin_port        = htons(port);
		nativeAddr4.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
		memset(&(nativeAddr4.sin_zero), 0, sizeof(nativeAddr4.sin_zero));
		
		struct sockaddr_in6 nativeAddr6;
		nativeAddr6.sin6_len        = sizeof(struct sockaddr_in6);
		nativeAddr6.sin6_family     = AF_INET6;
		nativeAddr6.sin6_port       = htons(port);
		nativeAddr6.sin6_flowinfo   = 0;
		nativeAddr6.sin6_addr       = in6addr_loopback;
		nativeAddr6.sin6_scope_id   = 0;
		
		// Wrap the native address structures
		
		NSData *address4 = [NSData dataWithBytes:&nativeAddr4 length:sizeof(nativeAddr4)];
		NSData *address6 = [NSData dataWithBytes:&nativeAddr6 length:sizeof(nativeAddr6)];
		
		addresses = [NSMutableArray arrayWithCapacity:2];
		[addresses addObject:address4];
		[addresses addObject:address6];
	}
	else
	{
		NSString *portStr = [NSString stringWithFormat:@"%hu", port];
		
		struct addrinfo hints, *res, *res0;
		
		memset(&hints, 0, sizeof(hints));
		hints.ai_family   = PF_UNSPEC;
		hints.ai_socktype = SOCK_STREAM;
		hints.ai_protocol = IPPROTO_TCP;
		
		int gai_error = getaddrinfo([host UTF8String], [portStr UTF8String], &hints, &res0);
		
		if (gai_error)
		{
			error = [self gaiError:gai_error];
		}
		else
		{
			NSUInteger capacity = 0;
			for (res = res0; res; res = res->ai_next)
			{
				if (res->ai_family == AF_INET || res->ai_family == AF_INET6) {
					capacity++;
				}
			}
			
			addresses = [NSMutableArray arrayWithCapacity:capacity];
			
			for (res = res0; res; res = res->ai_next)
			{
				if (res->ai_family == AF_INET)
				{
					// Found IPv4 address.
					// Wrap the native address structure, and add to results.
					
					NSData *address4 = [NSData dataWithBytes:res->ai_addr length:res->ai_addrlen];
					[addresses addObject:address4];
				}
				else if (res->ai_family == AF_INET6)
				{
					// Found IPv6 address.
					// Wrap the native address structure, and add to results.
                    
                    struct sockaddr_in6 *sockaddr = (struct sockaddr_in6 *)res->ai_addr;//akhil johny
                    					in_port_t *portPtr = &sockaddr->sin6_port;        //
                					if ((portPtr != NULL) && (*portPtr == 0)) {            //
                        					        *portPtr = htons(port);                // akhil johny
                                    }

					
					NSData *address6 = [NSData dataWithBytes:res->ai_addr length:res->ai_addrlen];
					[addresses addObject:address6];
				}
			}
			freeaddrinfo(res0);
			
			if ([addresses count] == 0)
			{
				error = [self gaiError:EAI_FAIL];
			}
		}
	}
	
	if (errPtr) *errPtr = error;
	return addresses;
}

**Comment by akhiljohny** [comment]
@Hardiktspaceo replace setIPv6Enabled in XMPPStream.m with

- (void)setIPv6Enabled:(BOOL)flag
{
	// Note: YES means kIPv6Disabled is OFF
	
	dispatch_block_t block = ^{
		
		if (flag)
			config &= ~kIPv6Disabled;
            // config |= kPreferIPv6; //akhil johny
        
            //config &= ~kPreferIPv6; //akhil johny
        
		else
			config |= kIPv6Disabled;
	};
	
	if (dispatch_get_specific(IsOnSocketQueueOrTargetQueueKey))
		block();
	else
		dispatch_async(socketQueue, block);
}

**Comment by akhiljohny** [comment]
@Hardiktspaceo  Replace lookupHost fun: in GCDAsyncSocket.m with

+ (NSMutableArray *)lookupHost:(NSString *)host port:(uint16_t)port error:(NSError **)errPtr
{
	LogTrace();
	
	NSMutableArray *addresses = nil;
	NSError *error = nil;
    
    
	
	if ([host isEqualToString:@"localhost"] || [host isEqualToString:@"loopback"])
	{
		// Use LOOPBACK address
		struct sockaddr_in nativeAddr4;
		nativeAddr4.sin_len         = sizeof(struct sockaddr_in);
		nativeAddr4.sin_family      = AF_INET;
		nativeAddr4.sin_port        = htons(port);
		nativeAddr4.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
		memset(&(nativeAddr4.sin_zero), 0, sizeof(nativeAddr4.sin_zero));
		
		struct sockaddr_in6 nativeAddr6;
		nativeAddr6.sin6_len        = sizeof(struct sockaddr_in6);
		nativeAddr6.sin6_family     = AF_INET6;
		nativeAddr6.sin6_port       = htons(port);
		nativeAddr6.sin6_flowinfo   = 0;
		nativeAddr6.sin6_addr       = in6addr_loopback;
		nativeAddr6.sin6_scope_id   = 0;
		
		// Wrap the native address structures
		
		NSData *address4 = [NSData dataWithBytes:&nativeAddr4 length:sizeof(nativeAddr4)];
		NSData *address6 = [NSData dataWithBytes:&nativeAddr6 length:sizeof(nativeAddr6)];
		
		addresses = [NSMutableArray arrayWithCapacity:2];
		[addresses addObject:address4];
		[addresses addObject:address6];
	}
	else
	{
		NSString *portStr = [NSString stringWithFormat:@"%hu", port];
		
		struct addrinfo hints, *res, *res0;
		
		memset(&hints, 0, sizeof(hints));
		hints.ai_family   = PF_UNSPEC;
		hints.ai_socktype = SOCK_STREAM;
		hints.ai_protocol = IPPROTO_TCP;
		
		int gai_error = getaddrinfo([host UTF8String], [portStr UTF8String], &hints, &res0);
		
		if (gai_error)
		{
			error = [self gaiError:gai_error];
		}
		else
		{
			NSUInteger capacity = 0;
			for (res = res0; res; res = res->ai_next)
			{
				if (res->ai_family == AF_INET || res->ai_family == AF_INET6) {
					capacity++;
				}
			}
			
			addresses = [NSMutableArray arrayWithCapacity:capacity];
			
			for (res = res0; res; res = res->ai_next)
			{
				if (res->ai_family == AF_INET)
				{
					// Found IPv4 address.
					// Wrap the native address structure, and add to results.
					
					NSData *address4 = [NSData dataWithBytes:res->ai_addr length:res->ai_addrlen];
					[addresses addObject:address4];
				}
				else if (res->ai_family == AF_INET6)
				{
					// Found IPv6 address.
					// Wrap the native address structure, and add to results.
                    
                    struct sockaddr_in6 *sockaddr = (struct sockaddr_in6 *)res->ai_addr;//akhil johny
                    					in_port_t *portPtr = &sockaddr->sin6_port;        //
                					if ((portPtr != NULL) && (*portPtr == 0)) {            //
                        					        *portPtr = htons(port);                // akhil johny
                                    }

					
					NSData *address6 = [NSData dataWithBytes:res->ai_addr length:res->ai_addrlen];
					[addresses addObject:address6];
				}
			}
			freeaddrinfo(res0);
			
			if ([addresses count] == 0)
			{
				error = [self gaiError:EAI_FAIL];
			}
		}
	}
	
	if (errPtr) *errPtr = error;
	return addresses;
}

**Comment by Hardiktspaceo** [comment]
ok thank you bro...

**Comment by Hardiktspaceo** [comment]
ok thank you.. i will check with this code

**Comment by akhiljohny** [comment]
@Hardiktspaceo  Replace setIPv6Enabled in GCDAsyncSocket.m  with

- (void)setIPv6Enabled:(BOOL)flag
{
	// Note: YES means kIPv6Disabled is OFF
	
	dispatch_block_t block = ^{
		
		if (flag)
			config &= ~kIPv6Disabled;
            // config |= kPreferIPv6; //akhil johny
        
            //config &= ~kPreferIPv6; //akhil johny
        
		else
			config |= kIPv6Disabled;
	};
	
	if (dispatch_get_specific(IsOnSocketQueueOrTargetQueueKey))
		block();
	else
		dispatch_async(socketQueue, block);
}

**Comment by akhiljohny** [comment]
Replace -(id)init func in XMPPStream.m with

- (id)init
{
	if ((self = [super init]))
	{
		// Common initialization
		[self commonInit];
		
		// Initialize socket
		asyncSocket = [[GCDAsyncSocket alloc] initWithDelegate:self delegateQueue:xmppQueue];
        
        asyncSocket.IPv4PreferredOverIPv6 = NO; // akhil johny
	}
	return self;
}

**Comment by akhiljohny** [comment]
@Hardiktspaceo  Hope this works

**Comment by Hardiktspaceo** [comment]
yes i try with  asyncSocket.IPv4PreferredOverIPv6 = NO; and just setup IPv6 WiFi network in my mac and check. problem solve with this one line.

**Comment by akhiljohny** [comment]
@Hardiktspaceo  ok  :)

**Comment by Hardiktspaceo** [comment]
@akhiljohny. Thank you so much issue solve. asyncSocket.IPv4PreferredOverIPv6 = NO; This line is life saving for me. 👍

**Comment by jigar2017** [comment]
@akhiljohny @ankits16 i try this code [asyncSocket setPreferIPv4OverIPv6:NO];.in ipv6 wifi network working perfect but ipv4 network connection issue
